version: '3.8'
services:
  php:
    build: ./PHP
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./PHP:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
      - db



